#!/bin/bash
#
# Uncomment the desired frequency.
# Only one line can be uncommented.
#
#
# 20m
#sudo /home/pi/rtlsdr-wsprd/rtlsdr_wsprd -f 14.0956M -c K6FTP -l DM04bk -d 2 -S  >> /var/log/wspr-receive.log 2>&1

# 30m
/home/pi/rtlsdr-wsprd/rtlsdr_wsprd -f  10.1387 -c K6FTP -l DM04bk -d 2 -S  >> /home/pi/wspr-receive.log 2>&1
#
# 40m
#/home/pi/rtlsdr-wsprd/rtlsdr_wsprd -f  7.0386 -c K6FTP -l DM04bk -d 2 -S  >> /home/pi/wspr-receive.log 2>&1

